# Generated by Django 4.2.4 on 2023-08-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bubble', '0002_leaf_bubble_user_terminal_bubble_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubble.terminal_bubble')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leaf_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubble.leaf_bubble')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
