# Generated by Django 4.2.4 on 2023-08-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal_permission',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terminal_permission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terminal_permission',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
