# Generated by Django 4.2.4 on 2023-08-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0003_remove_leaf_bubble_user_remove_terminal_bubble_user'),
        ('user', '0002_remove_user_date_of_birth_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bubble.terminal_bubble'),
        ),
    ]
